import type { Aggregate } from "../schema/aggregate.ts";
import type { Context } from "../schema/context.ts";
import type { DomainModel } from "../schema/domainModel.ts";
import { aggregateDesignCanvas } from "../canvases/aggregateDesignCanvas.ts";
import { boundedContextCanvas } from "../canvases/boundedContextCanvas.ts";
import { contextMap } from "../canvases/contextMap.ts";
import { eventModelFlow } from "../canvases/eventModelFlow.ts";
import { eventModelSlices } from "../canvases/eventModelSlices.ts";
import { exampleMap } from "../canvases/exampleMap.ts";
import { slug } from "./slug.ts";

export interface OutputFile {
  readonly path: string;
  readonly content: string;
}

const HEADER =
  "<!-- Generated by ddd-generate — do not edit. Update the model and regenerate. -->";

const isModeled = (context: Context): boolean => context.aggregates.length > 0;

const withHeader = (file: OutputFile): OutputFile => ({
  path: file.path,
  content: `${HEADER}\n\n${file.content}`,
});

const aggregateFile = (context: Context, aggregate: Aggregate): OutputFile => ({
  path: `${slug(context.id)}/${slug(aggregate.id)}.aggregate.md`,
  content: `${aggregateDesignCanvas(aggregate)}\n\n${exampleMap(aggregate)}`,
});

const contextFiles = (context: Context): OutputFile[] => [
  { path: `${slug(context.id)}/bounded-context.md`, content: boundedContextCanvas(context) },
  ...context.aggregates.map((aggregate) => aggregateFile(context, aggregate)),
  { path: `${slug(context.id)}/event-model-slices.md`, content: eventModelSlices(context) },
];

export const renderModel = (model: DomainModel): OutputFile[] =>
  [
    { path: "context-map.md", content: contextMap(model) },
    ...model.contexts.filter(isModeled).flatMap(contextFiles),
    ...model.flows.map((flow) => ({
      path: `flows/${slug(flow.name)}.md`,
      content: eventModelFlow(model, flow),
    })),
  ].map(withHeader);
